cache:
  manager:
    fallbackToNoOpCache: true
    caffeineCaches:
      - names: [ apikey ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ tenantByCode ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ tenantById ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ userBySubjectId ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 5
        expireAfterAccessMinutes: 5
        refreshAfterWriteMinutes: 5
      - names: [ authorizationAffiliatedNodes ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 1
        expireAfterAccessMinutes: 1
        refreshAfterWriteMinutes: 1
      - names: [ authorizationPrincipalNodeResource ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 1
        expireAfterAccessMinutes: 1
        refreshAfterWriteMinutes: 1
      - names: [ authorizationAffiliatedEdges ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 1
        expireAfterAccessMinutes: 1
        refreshAfterWriteMinutes: 1
      - names: [ authorizationPrincipalEdgeResource ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 1
        expireAfterAccessMinutes: 1
        refreshAfterWriteMinutes: 1
      - names: [ nodeConfig ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ edgeConfig ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ nodeIndex ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
      - names: [ edgeIndex ]
        allowNullValues: true
        initialCapacity: 100
        maximumSize: 500
        enableRecordStats: false
        expireAfterWriteMinutes: 10
        expireAfterAccessMinutes: 10
        refreshAfterWriteMinutes: 10
    mapCaches:
  apiKey:
    name: apikey
    keyPattern: resolve_$keyhash$:v0
  userBySubjectId:
    name: userBySubjectId
    keyPattern: user_by_subject_$subject$:v0
  tenantByCode:
    name: tenantByCode
    keyPattern: tenant_by_code_$code$:v0
  authorizationAffiliatedNodes:
    name:   authorizationAffiliatedNodes
    keyPattern: authz_affiliated_nodes$user_id$_$permissions$:v0
  authorizationPrincipalNodeResource:
    name:   authorizationPrincipalNodeResource
    keyPattern: authz_principal_node_resource$user_id$_$entity_type$_$entity_id$:v0
  authorizationAffiliatedEdges:
    name:     authorizationAffiliatedEdges
    keyPattern: authz_affiliated_edges$user_id$_$permissions$:v0
  authorizationPrincipalEdgeResource:
    name:     authorizationPrincipalEdgeResource
    keyPattern: authz_principal_edge_resource$user_id$_$entity_type$_$entity_id$:v0
  nodeConfig:
    name:   nodeConfig
    keyPattern: node_config_$node$:v0
  edgeConfig:
    name:   edgeConfig
    keyPattern: edge_config_$edge$:v0
  nodeIndex:
    name: nodeIndex
    keyPattern: node_index_$node$:v0
  edgeIndex:
    name: edgeIndex
    keyPattern: edge_index_$edge$:v0
